*&---------------------------------------------------------------------*
*& Report ZDYNPR_TAB_WIZZARD
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZDYNPR_TAB_WIZZARD.

call screen 100.

*&SPWIZARD: FUNCTION CODES FOR TABSTRIP 'MY_TABSTRIP'
CONSTANTS: BEGIN OF C_MY_TABSTRIP,
             TAB1 LIKE SY-UCOMM VALUE 'FC_TAB1',
             TAB2 LIKE SY-UCOMM VALUE 'FC_TAB2',
             TAB3 LIKE SY-UCOMM VALUE 'FC_TAB3',
           END OF C_MY_TABSTRIP.
*&SPWIZARD: DATA FOR TABSTRIP 'MY_TABSTRIP'
CONTROLS:  MY_TABSTRIP TYPE TABSTRIP.
DATA:      BEGIN OF G_MY_TABSTRIP,
             SUBSCREEN   LIKE SY-DYNNR,
             PROG        LIKE SY-REPID VALUE 'ZDYNPR_TAB_WIZZARD',
             PRESSED_TAB LIKE SY-UCOMM VALUE C_MY_TABSTRIP-TAB1,
           END OF G_MY_TABSTRIP.
DATA:      OK_CODE LIKE SY-UCOMM.

*&SPWIZARD: OUTPUT MODULE FOR TS 'MY_TABSTRIP'. DO NOT CHANGE THIS LINE!
*&SPWIZARD: SETS ACTIVE TAB
MODULE MY_TABSTRIP_ACTIVE_TAB_SET OUTPUT.
  MY_TABSTRIP-ACTIVETAB = G_MY_TABSTRIP-PRESSED_TAB.
  CASE G_MY_TABSTRIP-PRESSED_TAB.
    WHEN C_MY_TABSTRIP-TAB1.
      G_MY_TABSTRIP-SUBSCREEN = '0110'.
    WHEN C_MY_TABSTRIP-TAB2.
      G_MY_TABSTRIP-SUBSCREEN = '0120'.
    WHEN C_MY_TABSTRIP-TAB3.
      G_MY_TABSTRIP-SUBSCREEN = '0130'.
    WHEN OTHERS.
*&SPWIZARD:      DO NOTHING
  ENDCASE.
ENDMODULE.

*&SPWIZARD: INPUT MODULE FOR TS 'MY_TABSTRIP'. DO NOT CHANGE THIS LINE!
*&SPWIZARD: GETS ACTIVE TAB
MODULE MY_TABSTRIP_ACTIVE_TAB_GET INPUT.
  OK_CODE = SY-UCOMM.
  CASE OK_CODE.
    WHEN C_MY_TABSTRIP-TAB1.
      G_MY_TABSTRIP-PRESSED_TAB = C_MY_TABSTRIP-TAB1.
    WHEN C_MY_TABSTRIP-TAB2.
      G_MY_TABSTRIP-PRESSED_TAB = C_MY_TABSTRIP-TAB2.
    WHEN C_MY_TABSTRIP-TAB3.
      G_MY_TABSTRIP-PRESSED_TAB = C_MY_TABSTRIP-TAB3.
    WHEN OTHERS.
*&SPWIZARD:      DO NOTHING
  ENDCASE.
ENDMODULE.
